[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "docs/.vitepress/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
