backend:
  name: github
  repo: yasminzy/apsab
media_folder: public/media
public_folder: /media
site_url: https://apsab.netlify.app
locale: id
editor:
  preview: false
collections:
  - name: ledps
    folder: docs/ledps/
    delete: false
    fields:
      - name: title
        widget: hidden
      - name: body
        widget: markdown

  - name: lkps
    delete: false
    files:
      - name: 1-tata-pamong-tata-kelola-dan-kerja-sama
        file: docs/lkps/1-tata-pamong-tata-kelola-dan-kerja-sama.md
        fields:
          - name: kerja-sama-tridharma-perguruan-tinggi
            widget: list
            fields:
              - name: jenis
                widget: select
                options:
                  - { label: Pendidikan, value: pendidikan }
                  - { label: Penelitian, value: penelitian }
                  - { label: Pengabdian kepada Masyarakat, value: pkm }

              - name: tingkat
                widget: select
                options:
                  - { label: Internasional, value: internasional }
                  - { label: Nasional, value: nasional }
                  - { label: Lokal/ Wilayah, value: lokal }

              - name: judul-kegiatan-kerja-sama
                widget: string

              - name: manfaat-bagi-ps-yang-diakreditasi
                widget: string

              - name: tanggal-awal-kerja-sama
                widget: datetime
                date_format: DD/MM/YYYY

              - name: tanggal-akhir-kerja-sama
                widget: datetime
                date_format: DD/MM/YYYY

              - name: bukti-kerja-sama
                widget: text

      - name: 2-mahasiswa
        file: docs/lkps/2-mahasiswa.md
        fields:
          - name: 
            fields:
              - name: 
                options:
                  - { label: , value:  }
      
      - name: 3-sumber-daya-manusia
        file: docs/lkps/3-sumber-daya-manusia.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 4-keuangan-sarana-dan-prasarana
        file: docs/lkps/4-keuangan-sarana-dan-prasarana.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 5-pendidikan
        file: docs/lkps/5-pendidikan.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 6-penelitian
        file: docs/lkps/6-penelitian.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 7-pengabdian-kepada-masyarakat
        file: docs/lkps/7-pengabdian-kepada-masyarakat.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 8-luaran-dan-capaian-tridharma-perguruan-tinggi
        file: docs/lkps/8-luaran-dan-capaian-tridharma-perguruan-tinggi.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
      
      - name: 9-penjaminan-mutu
        file: docs/lkps/9-penjaminan-mutu.md
        fields:
          - name: 
            widget: list
            fields:
              - name: 
                widget: select
                options:
                  - { label: , value:  }
